# Building a snap

# Create/verify  user accounts with build.snapcraft.io and ubuntu one 

# sudo snap install lxd && sudo lxd init      # if you don’t have LXD already
# sudo usermod -a -G lxd $USER && newgrp lxd  # if your user is not in the lxd group already
# sudo snap install --classic snapcraft       # if you don’t have snapcraft already

# git clone https://github.com/dvorka/hstr
# cd hstr

# cd ./dist && ./1-dist.sh && cd ..  #hmmmmm maybe this is not helpin

# snapcraft cleanbuild --debug


name: hstr
version: '1.24'
summary: Easily view, navigate, search and manage your command history.
description: |
  Are you looking for a command that you used recently? Do you want to avoid
  the need to write long commands over and over again despite you used them
  recently? Are you looking for a tool that is able to manage your favorite
  commands? HSTR is a command line utility that brings improved Bash and zsh
  command completion from the history.

grade: devel
confinement: devmode

parts:
  hstr-source:
    source: https://github.com/dvorka/hstr/archive/1.24.tar.gz
    plugin: autotools
    build-packages:
      - git
      - g++
      - make
      - yasm
      - autoconf
      - libtool
      - cmake
      - pkg-config
      - automake
      - build-essential
